# Generated by Django 6.0.1 on 2026-01-20 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amznstorage_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/'),
        ),
    ]
