# Generated by Django 6.0.1 on 2026-02-07 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amznstorage_app', '0002_document_image'),
        ('architect_app', '0008_alter_contract_phase_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('upload', models.FileField(upload_to='projects/%Y/%m/%d/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects_documents', to='architect_app.project')),
            ],
        ),
    ]
