# Generated by Django 6.0.1 on 2026-02-09 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amznstorage_app', '0003_docproject'),
        ('architect_app', '0008_alter_contract_phase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docproject',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_documents', to='architect_app.project'),
        ),
    ]
